// src/components/NavBar.tsx
import { Link, NavLink } from 'react-router-dom';

const linkClasses = ({ isActive }: { isActive: boolean }) =>
  `text-white px-3 py-2 rounded-md text-sm font-medium ${isActive ? 'bg-indigo-700' : 'hover:bg-indigo-600'}`;

function NavBar() {
  return (
    <nav className="flex items-center justify-between px-4 py-3 mb-6">
      <Link to="/" className="text-xl font-semibold text-white">
        SSSS-made-easy
      </Link>
      <div className="flex gap-2">
        <NavLink to="/" className={linkClasses} end>
          Home
        </NavLink>
        <NavLink to="/split" className={linkClasses}>
          Split
        </NavLink>
        <NavLink to="/combine" className={linkClasses}>
          Combine
        </NavLink>
      </div>
    </nav>
  );
}

export default NavBar;

// src/routes/NavBar.svelte
<script lang="ts">
        import { Navbar, NavBrand, NavHamburger, NavUl } from 'flowbite-svelte';
        import NavItem from './NavItem.svelte';

        function isActive(pathname: string, path: string) {
                if (path == '/') {
                        return pathname == path;
                }
                return pathname.indexOf(path) == 0;
        }
</script>

<Navbar  >
        {#snippet children({ hidden, toggle })}
                <NavBrand href="/">
                        <span class="self-center whitespace-nowrap text-xl font-semibold dark:text-white"> SSSS-made-easy </span>
                </NavBrand>
                <NavHamburger on:click={toggle} />
                <NavUl {hidden}>
                        <NavItem href="/">Home</NavItem>
                        <NavItem href="/split/">Split</NavItem>
                        <NavItem href="/combine/">Combine</NavItem>
                </NavUl>
        {/snippet}
</Navbar>
